// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQHyVsYuu0yFig7qaeelpsLgY9X5E9CvI',
    appId: '1:997193546287:web:22ae15f6991906e0a564da',
    messagingSenderId: '997193546287',
    projectId: 'miniproject-e03d0',
    authDomain: 'miniproject-e03d0.firebaseapp.com',
    storageBucket: 'miniproject-e03d0.firebasestorage.app',
    measurementId: 'G-3FNJSEGKJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVSW94wso0-gKXmtmM4SjoVwF5O9GMlTQ',
    appId: '1:997193546287:android:1da972f938893113a564da',
    messagingSenderId: '997193546287',
    projectId: 'miniproject-e03d0',
    storageBucket: 'miniproject-e03d0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQHyVsYuu0yFig7qaeelpsLgY9X5E9CvI',
    appId: '1:997193546287:web:ff76e3a6d003708da564da',
    messagingSenderId: '997193546287',
    projectId: 'miniproject-e03d0',
    authDomain: 'miniproject-e03d0.firebaseapp.com',
    storageBucket: 'miniproject-e03d0.firebasestorage.app',
    measurementId: 'G-90F37X7NSK',
  );
}
