// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYnKu6_K3qwCOvOhzJH3VpbzKXP4CPL3M',
    appId: '1:363386000872:web:9ab046acbe83f54a60c05d',
    messagingSenderId: '363386000872',
    projectId: 'ogminiproject',
    authDomain: 'ogminiproject.firebaseapp.com',
    storageBucket: 'ogminiproject.firebasestorage.app',
    measurementId: 'G-TSRHZ44TSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbOA0Y9SAykrI9i47pKXqUoG4nRrnCyA',
    appId: '1:363386000872:android:abb7261c602c60e260c05d',
    messagingSenderId: '363386000872',
    projectId: 'ogminiproject',
    storageBucket: 'ogminiproject.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYnKu6_K3qwCOvOhzJH3VpbzKXP4CPL3M',
    appId: '1:363386000872:web:606837d38a1c468060c05d',
    messagingSenderId: '363386000872',
    projectId: 'ogminiproject',
    authDomain: 'ogminiproject.firebaseapp.com',
    storageBucket: 'ogminiproject.firebasestorage.app',
    measurementId: 'G-HH8JTLX2J3',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwBahGSjYJFdvkhNemtmXRU3n8rNlPysk',
    appId: '1:363386000872:ios:66546b2f08d945d960c05d',
    messagingSenderId: '363386000872',
    projectId: 'ogminiproject',
    storageBucket: 'ogminiproject.firebasestorage.app',
    iosBundleId: 'com.example.miniProject',
  );
}
